### ISSUE TITLE
Can't use ExpEvent with v3

### ISSUE THREAD

**Issue by kc9jud** [ksmith0/evt2root#2]
I'm having trouble building evt2root and using ExpEvent -- no matter what combination of cmake options I try, the evt2root executable is creating root files that don't have an evtTree branch, but only a Mesytec_ADC_MADC32 tree. What options do I need to pass cmake to get evt2root to use ExpEvent?

**Comment by ksmith0** [comment]
Can you please post you ExpEvent files? Also, you may be interested in using the beta version 3 in the v3 branch, which is getting close to completion and does not require ExpEvent libraries.

**Comment by kc9jud** [comment]
Ah, maybe that's it... I'm using the v3 branch. How do I get scalers out with the new version?

**Comment by ksmith0** [comment]
I closed the issue, as it is off topic. As for the scalers it depends on the buffer format. Currently v3 doesn't support scalers for the nsclClassic or nsclUSB buffers. This is something that you could contribute or I will get to when I find some time.
